### ISSUE TITLE
Question - Keyboard

### ISSUE THREAD

**Issue by BrandowBuenos** [lyngogogog/Dell-7472-7572-Hackintosh-EFI#1]
Hi my dear friend. How are you?
First, **thanks for sharing your open core EFI.** Finally, I managed to migrate the clover to the open core, thanks to you.
My question is, are you having **problems with the keyboard**?
Everything works perfectly, but the keyboard doesn't turn on sometimes.

**Comment by amxiazhi** [comment]
俺也一样

**Comment by lyngogogog** [comment]
I have also encountered keyboard problems. Waking up the keyboard after sleep will resume work.

**Comment by BrandowBuenos** [comment]
> I have also encountered keyboard problems. Waking up the keyboard after sleep will resume work. 

Muito obrigado ! tentarei encontrar a solucao definitiva e deixo vocês informados, se encontrar a solução.

**Comment by BrandowBuenos** [comment]
> I have also encountered keyboard problems. Waking up the keyboard after sleep will resume work. 

Thank you !  I will try to find the definitive solution and let you know if I find them.

**Comment by lyngogogog** [comment]
> > I have also encountered keyboard problems. Waking up the keyboard after sleep will resume work.
> 
> Thank you ! I will try to find the definitive solution and let you know if I find them.

Thank you！！！

**Comment by BrandowBuenos** [comment]
Leaving the keyboard aside a little, I found that by adding the **HWPEnable** (https://github.com/headkaze/HWPEnable) , the performance of the laptop increases a lot. Here's the tip :)
